export const explanations = {
  1: "Sử dụng thì Quá khứ tiếp diễn (Past Continuous) cho hành động đang diễn ra trong quá khứ. Cấu trúc: was/were + V-ing. 'While' (trong khi) là dấu hiệu của hành động đang xảy ra song song trong quá khứ.",
  2: "Sử dụng thì Quá khứ đơn (Past Simple) với 'two months ago' - dấu hiệu thời gian cụ thể trong quá khứ. Động từ 'sell' ở dạng quá khứ là 'sold'.",
  3: "Sử dụng so sánh hơn (Comparative) với 'than'. Cấu trúc: adj/adv + -er + than. 'Early' → 'earlier'.",
  4: "Câu hỏi ở thì Quá khứ đơn (Past Simple). Cấu trúc: Did + S + V(nguyên thể)? 'Did' được dùng cho tất cả các ngôi.",
  5: "Sử dụng trạng từ 'terribly' để bổ nghĩa cho tính từ 'tired'. Cấu trúc: adv + adj. Không dùng tính từ 'terrible' trong trường hợp này.",
  6: "Sử dụng thì Quá khứ đơn 'saw' vì đây là hành động ngắn xen vào hành động đang diễn ra. Cấu trúc: S + was/were + V-ing + when + S + V(ed/V2).",
  7: "Sử dụng so sánh nhất (Superlative) với 'of all three'. Cấu trúc: the + adj-est / the most + adj. 'Famous' với so sánh nhất là 'the least famous' (ít nổi tiếng nhất).",
  8: "Sử dụng đại từ quan hệ sở hữu 'whose' để chỉ sự sở hữu. 'Whose father' = cha của cậu ấy.",
  9: "Sử dụng từ để hỏi 'where' để hỏi về địa điểm, vị trí. 'Where to put' = đặt ở đâu.",
  10: "Sử dụng đại từ quan hệ 'who' để thay thế cho người (Mark). 'Who' đứng giữa hai dấu phẩy trong mệnh đề quan hệ không xác định.",
  11: "Phrasal verb: 'take up' = bắt đầu một hoạt động/sở thích mới. 'Take up a sport' = bắt đầu chơi một môn thể thao.",
  12: "Phrasal verb: 'turn down' = từ chối. 'Turn down an offer' = từ chối một lời đề nghị.",
  13: "Động từ: 'nod' = gật đầu (đồng ý). Phù hợp với ngữ cảnh đồng ý khi được đề xuất đi dạo.",
  14: "Danh từ: 'death' = cái chết. 'After his mother's death' = sau khi mẹ anh ấy qua đời.",
  15: "Tính từ: 'incredible' = không thể tin được, đáng kinh ngạc. Phù hợp với ngữ cảnh không ai bị thương trong tai nạn.",
  16: "Giới từ: 'afraid of' = sợ hãi cái gì. Cụm cố định với tính từ 'afraid'.",
  17: "Thành ngữ: 'in their power' = trong khả năng của họ. 'Do everything in one's power' = làm mọi thứ có thể.",
  18: "Động từ: 'matches' = hợp với, phù hợp với. Chủ ngữ 'a leather bag' là số ít nên dùng 'matches'.",
  19: "Danh từ: 'imagination' = trí tưởng tượng. 'Vivid imagination' = trí tưởng tượng phong phú.",
  20: "Thành ngữ: 'have the impression that' = có ấn tượng rằng, cảm thấy rằng.",
  21: "Sử dụng thì Hiện tại tiếp diễn 'is thinking' để diễn tả suy nghĩ đang xảy ra, có thể thay đổi. 'Think of' = nghĩ về, suy nghĩ về.",
  22: "Sử dụng thì Hiện tại đơn 'don't mind' vì 'mind' là động từ trạng thái (stative verb), không dùng với tiếp diễn.",
  23: "Sử dụng thì Hiện tại tiếp diễn 'are flying' để diễn tả kế hoạch trong tương lai đã sắp xếp. 'At 9:00 tomorrow' là thời gian cụ thể.",
  24: "Từ để hỏi: 'Which' = cái nào (chọn trong số nhiều lựa chọn). 'Which city' = thành phố nào.",
  25: "Từ để hỏi: 'How much' = bao nhiêu (cho danh từ không đếm được hoặc giá cả). 'How much do they charge' = họ tính phí bao nhiêu.",
  26: "Từ để hỏi: 'Who' = ai. 'Who is talking to' = đang nói chuyện với ai.",
  27: "Câu phủ định ở thì Quá khứ đơn. Cấu trúc: S + didn't + V(nguyên thể).",
  28: "Used to: 'used to be' = đã từng là (trong quá khứ). Diễn tả trạng thái trong quá khứ không còn đúng ở hiện tại.",
  29: "Sử dụng thì Quá khứ đơn 'tried' vì có thời gian cụ thể 'twice'. Không dùng 'used to' vì không phải thói quen.",
  30: "Get used to + V-ing: 'got used to waking' = dần quen với việc thức dậy. Diễn tả quá trình làm quen với điều gì.",
  31: "Giới từ: 'recover from' = hồi phục từ. Cụm động từ cố định.",
  32: "Thành ngữ: 'take place' = diễn ra, xảy ra. 'The exhibition took place' = triển lãm diễn ra.",
  33: "Động từ: 'expect' = mong đợi. 'Expect someone to do something' = mong đợi ai đó làm gì.",
  34: "Giới từ: 'on the map' = trên bản đồ. Cụm cố định.",
  35: "Danh từ: 'sights' = các danh lam thắng cảnh. 'Looking at the sights' = ngắm nhìn các thắng cảnh.",
  36: "Danh từ: 'job' = công việc (đếm được). 'Find a job' = tìm một công việc.",
  37: "Giới từ: 'belong to' = thuộc về. Cụm động từ cố định.",
  38: "Thành ngữ: 'take no notice of' = không chú ý đến, không để ý đến.",
  39: "Giới từ: 'argue with' = tranh cãi với. Cụm động từ cố định.",
  40: "Giới từ: 'consist of' = bao gồm. Cụm động từ cố định.",
  41: "Sử dụng thì Tương lai tiếp diễn 'will be taking' để diễn tả hành động đang diễn ra tại một thời điểm cụ thể trong tương lai.",
  42: "Sử dụng thì Tương lai đơn 'will have' với 'as soon as' (ngay khi). Diễn tả hành động sẽ xảy ra sau một hành động khác.",
  43: "Sử dụng thì Tương lai hoàn thành 'have finished' với 'by tomorrow'. Cấu trúc: Will + S + have + V3?",
  44: "Sử dụng 'is going to be' để diễn tả dự đoán dựa trên bằng chứng hiện tại (xe đang chạy rất nhanh).",
  45: "Câu điều kiện loại 2 (unreal present): If + S + V(ed/V2), S + would/could + V(inf). Diễn tả điều không có thật ở hiện tại.",
  46: "Câu điều kiện loại 2: 'If I lived' = nếu tôi sống (nhưng thực tế không sống). Dùng 'lived' (quá khứ đơn) trong mệnh đề if.",
  47: "Sử dụng 'some' trong câu hỏi lịch sự (requests). 'Could I have some' = tôi có thể có thêm một chút.",
  48: "Sử dụng 'too much' với danh từ không đếm được (sugar). 'Too much' = quá nhiều.",
  49: "Sử dụng 'How many' với danh từ đếm được (teachers). 'How many teachers' = bao nhiêu giáo viên.",
  50: "Sử dụng 'a few' (một vài) với danh từ đếm được trong câu khẳng định. 'A few more things' = một vài điều nữa.",
  51: "Thành ngữ: 'put the final touches' = hoàn thiện những chi tiết cuối cùng.",
  52: "Thành ngữ: 'put in a good word for someone' = nói tốt về ai đó, giúp đỡ ai bằng lời nói.",
  53: "Phrasal verb: 'give up' = từ bỏ. 'Give up trying' = từ bỏ việc cố gắng.",
  54: "Phrasal verb: 'give out' = phát, phân phát. 'Give out leaflets' = phát tờ rơi.",
  55: "Phrasal verb: 'put off' = hoãn lại, trì hoãn. 'Put off the meeting' = hoãn cuộc họp.",
  56: "Phrasal verb: 'show off' = khoe khoang. 'Show off his car' = khoe chiếc xe của anh ấy.",
  57: "Phrasal verb: 'get off' = xuống (xe). 'Get off the bus' = xuống xe buýt.",
  58: "Giới từ: 'according to' = theo như. Cụm giới từ cố định.",
  59: "Giới từ: 'succeed in' = thành công trong. Cụm động từ cố định.",
  60: "Thành ngữ: 'make it to the top' = đạt đến đỉnh cao, thành công.",
  61: "Sử dụng Present Perfect 'have been to' = đã từng đến. 'Been to' diễn tả kinh nghiệm đi đến và đã trở về.",
  62: "Sử dụng 'ever' trong câu hỏi với Present Perfect. 'Have you ever' = bạn đã bao giờ.",
  63: "Sử dụng Present Perfect Continuous 'has been playing' với 'since' để diễn tả hành động bắt đầu trong quá khứ và tiếp tục đến hiện tại.",
  64: "Sử dụng 'since' với Present Perfect Continuous để chỉ mốc thời gian bắt đầu. 'Since our plane took off' = kể từ khi máy bay cất cánh.",
  65: "Sử dụng 'has to' = phải (nghĩa vụ từ bên ngoài). 'Has to go' = phải đi.",
  66: "Sử dụng 'have to' = phải. 'We have to work' = chúng tôi phải làm việc.",
  67: "Sử dụng 'would rather' = thích... hơn. Cấu trúc: would rather + V(inf) + than + V(inf).",
  68: "Sử dụng 'needn't' = không cần. 'Needn't wait' = không cần đợi.",
  69: "Sử dụng 'must' để diễn tả suy luận chắc chắn (95-99%). 'She must still be' = chắc hẳn cô ấy vẫn đang.",
  70: "Sử dụng 'had better' = nên (lời khuyên mạnh). 'Had better see' = nên đi khám.",
  71: "Phrasal verb: 'come down with' = mắc bệnh. 'Come down with the flu' = bị cúm.",
  72: "Phrasal verb: 'come up with' = nghĩ ra. 'Come up with ideas' = nghĩ ra ý tưởng.",
  73: "Thành ngữ: 'for ages' = lâu lắm rồi. Dùng với Present Perfect.",
  74: "Giới từ: 'intention of' = ý định làm gì. Cụm danh từ cố định.",
  75: "Giới từ: 'interested in' = quan tâm đến. Cụm tính từ cố định.",
  76: "Thành ngữ: 'take into consideration' = xem xét, cân nhắc.",
  77: "Phrasal verb: 'look forward to' = mong đợi, trông chờ. Sau 'to' là V-ing.",
  78: "Thành ngữ: 'do one's best' = cố gắng hết sức. 'Did his best' = đã cố gắng hết sức.",
  79: "Thành ngữ: 'do someone good' = có lợi cho ai. Sau 'do' dùng tân ngữ + 'good' (danh từ).",
  80: "Phrasal verb: 'get on well with' = hòa thuận với, có quan hệ tốt với.",
  81: "Sử dụng Modal Perfect 'could have been killed' = có thể đã bị giết. Diễn tả khả năng trong quá khứ nhưng không xảy ra.",
  82: "Câu điều kiện loại 3 (unreal past): If + S + had (not) + V3, S + would/could + have + V3. 'Hadn't been' = đã không.",
  83: "Câu điều kiện loại 3: 'wouldn't have finished' = đã không thể hoàn thành. Diễn tả kết quả không xảy ra trong quá khứ.",
  84: "Câu điều kiện loại 3: 'hadn't seen' = đã không nhìn thấy. Dùng Past Perfect trong mệnh đề if.",
  85: "Sử dụng 'wish' + S + could + V(inf) để diễn tả ước muốn ở hiện tại. 'I wish I could' = tôi ước tôi có thể.",
  86: "Sử dụng 'If only' + S + had + V3 để diễn tả hối tiếc về quá khứ. 'Had arrived' = đã đến.",
  87: "Sử dụng 'wish' + S + hadn't + V3 để diễn tả hối tiếc về quá khứ. 'Hadn't made' = đã không mắc phải.",
  88: "Sử dụng 'Neither of' = không cái nào trong hai. 'Neither of these two books' = không cuốn nào trong hai cuốn sách này.",
  89: "Sử dụng 'Both' = cả hai. 'Both Ian and Gerry' = cả Ian và Gerry.",
  90: "Sử dụng 'All' = tất cả (từ 3 trở lên). 'All four of my friends' = cả bốn người bạn của tôi.",
  91: "Thành ngữ: 'go through my mind' = nảy ra trong đầu tôi, tôi nghĩ đến.",
  92: "Thành ngữ: 'go wrong' = xảy ra sai sót, hỏng hóc.",
  93: "Thành ngữ: 'go red' = đỏ mặt (vì xấu hổ, ngại ngùng).",
  94: "Thành ngữ: 'go bad' = bị hỏng, bị thối (thực phẩm).",
  95: "Sử dụng 'at last' = cuối cùng, sau một thời gian chờ đợi.",
  96: "Sử dụng 'lately' = gần đây. 'Hasn't been feeling well lately' = gần đây không được khỏe.",
  97: "Sử dụng 'late' = muộn. 'Have dinner late' = ăn tối muộn.",
  98: "Sử dụng 'at least' = ít nhất. 'At least phone me' = ít nhất hãy gọi cho tôi.",
  99: "Thành ngữ: 'once and for all' = một lần và mãi mãi, giải quyết dứt điểm.",
  100: "Thành ngữ: 'All in all' = nhìn chung, xét trên tổng thể."
};

export const getExplanation = (questionId) => {
  return explanations[questionId] || "Giải thích chi tiết sẽ được cập nhật sớm.";
};
